#!/bin/bash
# Post scheduled tweets for Feb 22, 2026 at 12:15 IST
# Generated by tweet scheduler cron at 08:43 IST

cd /Users/ay/code/northstar

# Download fresh cosmic images
curl -sL -o /tmp/northstar_image.jpg 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=800&h=800&fit=crop'
curl -sL -o /tmp/hanuman_image.jpg 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=800&h=800&fit=crop'

# @northstar_astro - Insight tweet (Pisces Sun Season + Neptune)
export NORTHSTAR_TWEET='Pisces season is here, but this one hits different.

Neptune has been dissolving boundaries in its home sign for 14 years. This is its final Pisces season before the shift.

The dreams you couldn'\''t let go of? They'\''re about to become real or release you. 🌊✨

#PiscesSeason #Astrology'

# @angry_hanuman - Meme tweet (Virgo roast)
export HANUMAN_TWEET='POV: You'\''re a Virgo Mercury trying to explain to someone why their "vibes-based decision making" is actually a 73-step logical fallacy 💀📋

"No I'\''m not being critical, I'\''m being ACCURATE"

#Virgo #MercuryMemes'

node scripts/tweet-with-media.js

echo "Posted at $(date)"
