#!/bin/bash
# Post scheduled tweets for Feb 22, 2026 at 09:42 IST
# Generated by tweet scheduler cron

cd /Users/ay/code/northstar

# Download fresh cosmic images
curl -sL -o /tmp/northstar_image.jpg 'https://images.unsplash.com/photo-1507400492013-162706c8c05e?w=800&h=800&fit=crop'
curl -sL -o /tmp/hanuman_image.jpg 'https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=800&h=800&fit=crop'

# @northstar_astro - Insight tweet (Neptune/Pisces focus)
export NORTHSTAR_TWEET='Neptune has been in Pisces since 2011. 

For 14 years, the veil between worlds has been thin — beautiful illusions, spiritual awakenings, and collective dreams.

In 2026, Neptune leaves. The fog lifts. Reality returns. 🌊✨

Are you ready to see clearly?

#Astrology #Neptune'

# @angry_hanuman - Meme tweet (Capricorn roast)
export HANUMAN_TWEET='Capricorn placements don'\''t have control issues, they have "I'\''ve already calculated 47 ways this could go wrong and prepared contingency plans for each" issues 💀🐐

Saturn said: trust no one, plan everything.

#Capricorn #AstrologyMemes'

node scripts/tweet-with-media.js

echo "Posted at $(date)"
